apiVersion: apps/v1
kind: Deployment
metadata:
  name: how-to-cloud-k8s-web
spec:
  selector:
    matchLabels:
      app: htc-web-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: htc-web-k8s
    spec:
      containers:
      - name: htc-web-k8s
        image: how-to-cloud-web:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"     
        ports:
        - containerPort: 8080