apiVersion: v1
kind: Service
metadata:
  name: how-to-cloud-k8s-bg
spec:
  selector:
    app: htc-background-k8s
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 0.0.0.0